#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := christmas
IDF_PATH := ../idf
TOOLCHAIN := ../xtensa-esp32-elf/bin

include $(IDF_PATH)/make/project.mk

